version: "3.8"
services:
  db:
      image: postgres:14
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./init_databases.sql:/docker-entrypoint-initdb.d/init_databases.sql
      env_file:
        - .env.local
      ports:
        - "5432:5432"
  auth_service:
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    ports:
      - "8000:8000"
    env_file:
    - .env.local
    depends_on:
      - db
      - redis
  
  roles_service:
    build:
      context: .
      dockerfile: ./roles_service/Dockerfile
    ports:
      - "8001:8001"
    env_file:
    - .env.local  
    depends_on:
      - db
      - auth_service

  fields_service:
    build:
      context: .
      dockerfile: ./fields_service/Dockerfile
    ports:
      - "8002:8002"
    env_file:
    - .env.local
    depends_on:
      - db

  reservations_service:
    build:
      context: .
      dockerfile: ./reservations_service/Dockerfile
    ports:
      - "8003:8003"
    env_file:
    - .env.local
    depends_on:
      - db
      - redis

  admin_dashboard:
    build:
      context: .
      dockerfile: ./admin_dashboard/Dockerfile
    ports:
      - "8004:8004"
    env_file:
    - .env.local
    depends_on:
      - db
      - redis

  

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data: