version: "3.8"
services:
  auth_service:
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/auth_db
    depends_on:
      - db
      - redis
  
  roles_service:
    build:
      context: .
      dockerfile: ./roles_service/Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - db

  fields_service:
    build:
      context: .
      dockerfile: ./fields_service/Dockerfile
    ports:
      - "8002:8000"
    depends_on:
      - db

  reservations_service:
    build:
      context: .
      dockerfile: ./reservations_service/Dockerfile
    ports:
      - "8003:8000"
    depends_on:
      - db
      - redis

  admin_dashboard:
    build:
      context: .
      dockerfile: ./admin_dashboard/Dockerfile
    ports:
      - "8004:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.local
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"